import { useEffect, useState } from "react"
import { Calander } from "./calander"
import { NewCalander } from "./newCalander"
import { NewEvent } from "./newEvent"
export const Main = () => {
const [name,setName]=useState("Calander")
const [bacColor,setBacColor]=useState()
const [colorTest,setcolorTest]=useState()
const [flag,setflag]=useState(false)
const add=()=>{
    setflag(true)
    window.localStorage.setItem(name,JSON.stringify(basicCalender))
    const s=JSON.parse(window.localStorage.getItem(name))
 }
   const[basicCalender,setBasicCalender]=useState({//אוביקט- אחד המאפינים-מערך של חודשים
   Mounths: [
       {
           name: 'תשרי',
           Days: [
               { name: 'א', dayOfWeek: 3, events: [{ type: '🍎', text: 'א דראש השנה' }] },
               { name: 'ב', dayOfWeek: 4, events: [{ type: '🍎', text: 'ב דראש השנה' }] },
               { name: 'ג', dayOfWeek: 5, events: [{ type: '❎', text: 'צום גדליה' }] },
               { name: 'ד', dayOfWeek: 6, events: [] },
               { name: 'ה', dayOfWeek: 7, events: [] },
               { name: 'ו', dayOfWeek: 1, events: [] },
               { name: 'ז', dayOfWeek: 2, events: [] },
               { name: 'ח', dayOfWeek: 3, events: [] },
               { name: 'ט', dayOfWeek: 4, events: [] },
               { name: 'י', dayOfWeek: 5, events: [{ type: '❎', text: 'יום הכיפורים' }] },
               { name: 'יא', dayOfWeek: 6, events: [] },
               { name: 'יב', dayOfWeek: 7, events: [] },
               { name: 'יג', dayOfWeek: 1, events: [] },
               { name: 'יד', dayOfWeek: 2, events: [] },
               { name: 'טו', dayOfWeek: 3, events: [{ type: '🍋', text: 'יום טוב סוכות' }] },
               { name: 'טז', dayOfWeek: 4, events: [{ type: '🍋', text: 'א דחול המועד' }] },
               { name: 'יז', dayOfWeek: 5, events: [{ type: '🍋', text: 'ב דחול המועד' }] },
               { name: 'יח', dayOfWeek: 6, events: [{ type: '🍋', text: 'ג דחול המועד' }] },
               { name: 'יט', dayOfWeek: 7, events: [{ type: '🍋', text: 'ד דחול המועד' }] },
               { name: 'כ', dayOfWeek: 1, events: [{ type: '🍋', text: 'ה דחול המועד' }] },
               { name: 'כא', dayOfWeek: 2, events: [{ type: '🌿', text: 'הושענא רבא' }] },
               { name: 'כב', dayOfWeek: 3, events: [{ type: '📖', text: 'שמיני עצרת ושמחת תורה' }] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [] },
               { name: 'כו', dayOfWeek: 7, events: [] },
               { name: 'כז', dayOfWeek: 1, events: [] },
               { name: 'כח', dayOfWeek: 2, events: [] },
               { name: 'כט', dayOfWeek: 3, events: [] },
               { name: 'ל', dayOfWeek: 4, events: [] },
           ]
       },
       {
           name: 'חשוון',
           Days: [
               { name: 'א', dayOfWeek: 5, events: [] },
               { name: 'ב', dayOfWeek: 6, events: [] },
               { name: 'ג', dayOfWeek: 4, events: [] },
               { name: 'ד', dayOfWeek: 5, events: [] },
               { name: 'ה', dayOfWeek: 6, events: [] },
               { name: 'ו', dayOfWeek: 7, events: [] },
               { name: 'ז', dayOfWeek: 1, events: [] },
               { name: 'ח', dayOfWeek: 2, events: [] },
               { name: 'ט', dayOfWeek: 3, events: [] },
               { name: 'י', dayOfWeek: 4, events: [] },
               { name: 'יא', dayOfWeek: 5, events: [] },
               { name: 'יב', dayOfWeek: 6, events: [] },
               { name: 'יג', dayOfWeek: 4, events: [] },
               { name: 'יד', dayOfWeek: 5, events: [] },
               { name: 'טו', dayOfWeek: 6, events: [] },
               { name: 'טז', dayOfWeek: 7, events: [] },
               { name: 'יז', dayOfWeek: 1, events: [] },
               { name: 'יח', dayOfWeek: 2, events: [] },
               { name: 'יט', dayOfWeek: 3, events: [] },
               { name: 'כ', dayOfWeek: 4, events: [] },
               { name: 'כא', dayOfWeek: 5, events: [] },
               { name: 'כב', dayOfWeek: 6, events: [] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [] },
               { name: 'כו', dayOfWeek: 7, events: [] },
               { name: 'כז', dayOfWeek: 1, events: [] },
               { name: 'כח', dayOfWeek: 2, events: [] },
               { name: 'כט', dayOfWeek: 3, events: [] },
           ]
       }, {
           name: 'כסלו',
           Days: [
               { name: 'א', dayOfWeek: 3, events: [] },
               { name: 'ב', dayOfWeek: 4, events: [] },
               { name: 'ג', dayOfWeek: 5, events: [] },
               { name: 'ד', dayOfWeek: 6, events: [] },
               { name: 'ה', dayOfWeek: 7, events: [] },
               { name: 'ו', dayOfWeek: 1, events: [] },
               { name: 'ז', dayOfWeek: 2, events: [] },
               { name: 'ח', dayOfWeek: 3, events: [] },
               { name: 'ט', dayOfWeek: 4, events: [] },
               { name: 'י', dayOfWeek: 5, events: [] },
               { name: 'יא', dayOfWeek: 6, events: [] },
               { name: 'יב', dayOfWeek: 7, events: [] },
               { name: 'יג', dayOfWeek: 1, events: [] },
               { name: 'יד', dayOfWeek: 2, events: [] },
               { name: 'טו', dayOfWeek: 3, events: [] },
               { name: 'טז', dayOfWeek: 4, events: [] },
               { name: 'יז', dayOfWeek: 5, events: [] },
               { name: 'יח', dayOfWeek: 6, events: [] },
               { name: 'יט', dayOfWeek: 7, events: [] },
               { name: 'כ', dayOfWeek: 1, events: [] },
               { name: 'כא', dayOfWeek: 2, events: [] },
               { name: 'כב', dayOfWeek: 3, events: [] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [{ type: '🕯️', text: 'חנוכה' }] },
               { name: 'כו', dayOfWeek: 7, events: [{ type: '🕯️', text: 'חנוכה' }] },
               { name: 'כז', dayOfWeek: 1, events: [{ type: '🕯️', text: 'חנוכה' }] },
               { name: 'כח', dayOfWeek: 2, events: [{ type: '🕯️', text: 'חנוכה' }] },
               { name: 'כט', dayOfWeek: 3, events: [{ type: '🕯️', text: 'חנוכה' }] },
               { name: 'ל', dayOfWeek: 4, events: [{ type: '🕯️', text: 'חנוכה' }] },
           ]
       },
       {
           name: 'טבת',
           Days: [
               { name: 'א', dayOfWeek: 5, events: [{ type: '🕯️', text: 'חנוכה' }] },
               { name: 'ב', dayOfWeek: 6, events: [{ type: '🕯️', text: 'חנוכה' }] },
               { name: 'ג', dayOfWeek: 4, events: [] },
               { name: 'ד', dayOfWeek: 5, events: [] },
               { name: 'ה', dayOfWeek: 6, events: [] },
               { name: 'ו', dayOfWeek: 7, events: [] },
               { name: 'ז', dayOfWeek: 1, events: [] },
               { name: 'ח', dayOfWeek: 2, events: [] },
               { name: 'ט', dayOfWeek: 3, events: [] },
               { name: 'י', dayOfWeek: 4, events: [{ type: '❎', text: 'צום עשרה בטבת' }] },
               { name: 'יא', dayOfWeek: 5, events: [] },
               { name: 'יב', dayOfWeek: 6, events: [] },
               { name: 'יג', dayOfWeek: 4, events: [] },
               { name: 'יד', dayOfWeek: 5, events: [] },
               { name: 'טו', dayOfWeek: 6, events: [] },
               { name: 'טז', dayOfWeek: 7, events: [] },
               { name: 'יז', dayOfWeek: 1, events: [] },
               { name: 'יח', dayOfWeek: 2, events: [] },
               { name: 'יט', dayOfWeek: 3, events: [] },
               { name: 'כ', dayOfWeek: 4, events: [] },
               { name: 'כא', dayOfWeek: 5, events: [] },
               { name: 'כב', dayOfWeek: 6, events: [] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [] },
               { name: 'כו', dayOfWeek: 7, events: [] },
               { name: 'כז', dayOfWeek: 1, events: [] },
               { name: 'כח', dayOfWeek: 2, events: [] },
               { name: 'כט', dayOfWeek: 3, events: [] },
           ]
       }, {
           name: 'שבט',
           Days: [
               { name: 'א', dayOfWeek: 3, events: [] },
               { name: 'ב', dayOfWeek: 4, events: [] },
               { name: 'ג', dayOfWeek: 5, events: [] },
               { name: 'ד', dayOfWeek: 6, events: [] },
               { name: 'ה', dayOfWeek: 7, events: [] },
               { name: 'ו', dayOfWeek: 1, events: [] },
               { name: 'ז', dayOfWeek: 2, events: [] },
               { name: 'ח', dayOfWeek: 3, events: [] },
               { name: 'ט', dayOfWeek: 4, events: [] },
               { name: 'י', dayOfWeek: 5, events: [] },
               { name: 'יא', dayOfWeek: 6, events: [] },
               { name: 'יב', dayOfWeek: 7, events: [] },
               { name: 'יג', dayOfWeek: 1, events: [] },
               { name: 'יד', dayOfWeek: 2, events: [] },
               { name: 'טו', dayOfWeek: 3, events: [{ type: '🍇', text: 'טו בשבט' }] },
               { name: 'טז', dayOfWeek: 4, events: [] },
               { name: 'יז', dayOfWeek: 5, events: [] },
               { name: 'יח', dayOfWeek: 6, events: [] },
               { name: 'יט', dayOfWeek: 7, events: [] },
               { name: 'כ', dayOfWeek: 1, events: [] },
               { name: 'כא', dayOfWeek: 2, events: [] },
               { name: 'כב', dayOfWeek: 3, events: [] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [] },
               { name: 'כו', dayOfWeek: 7, events: [] },
               { name: 'כז', dayOfWeek: 1, events: [] },
               { name: 'כח', dayOfWeek: 2, events: [] },
               { name: 'כט', dayOfWeek: 3, events: [] },
               { name: 'ל', dayOfWeek: 4, events: [] },
           ]
       },
       {
           name: 'אדר',
           Days: [
               { name: 'א', dayOfWeek: 5, events: [] },
               { name: 'ב', dayOfWeek: 6, events: [] },
               { name: 'ג', dayOfWeek: 4, events: [] },
               { name: 'ד', dayOfWeek: 5, events: [] },
               { name: 'ה', dayOfWeek: 6, events: [] },
               { name: 'ו', dayOfWeek: 7, events: [] },
               { name: 'ז', dayOfWeek: 1, events: [] },
               { name: 'ח', dayOfWeek: 2, events: [] },
               { name: 'ט', dayOfWeek: 3, events: [] },
               { name: 'י', dayOfWeek: 4, events: [] },
               { name: 'יא', dayOfWeek: 5, events: [] },
               { name: 'יב', dayOfWeek: 6, events: [] },
               { name: 'יג', dayOfWeek: 4, events: [{ type: '🤡', text: 'פורים דפרזים' }] },
               { name: 'יד', dayOfWeek: 5, events: [{ type: '🤡', text: 'פורים דמוקפים' }] },
               { name: 'טו', dayOfWeek: 6, events: [] },
               { name: 'טז', dayOfWeek: 7, events: [] },
               { name: 'יז', dayOfWeek: 1, events: [] },
               { name: 'יח', dayOfWeek: 2, events: [] },
               { name: 'יט', dayOfWeek: 3, events: [] },
               { name: 'כ', dayOfWeek: 4, events: [] },
               { name: 'כא', dayOfWeek: 5, events: [] },
               { name: 'כב', dayOfWeek: 6, events: [] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [] },
               { name: 'כו', dayOfWeek: 7, events: [] },
               { name: 'כז', dayOfWeek: 1, events: [] },
               { name: 'כח', dayOfWeek: 2, events: [] },
               { name: 'כט', dayOfWeek: 3, events: [] },
           ]
       }, {
           name: 'ניסן',
           Days: [
               { name: 'א', dayOfWeek: 3, events: [] },
               { name: 'ב', dayOfWeek: 4, events: [] },
               { name: 'ג', dayOfWeek: 5, events: [] },
               { name: 'ד', dayOfWeek: 6, events: [] },
               { name: 'ה', dayOfWeek: 7, events: [] },
               { name: 'ו', dayOfWeek: 1, events: [] },
               { name: 'ז', dayOfWeek: 2, events: [] },
               { name: 'ח', dayOfWeek: 3, events: [] },
               { name: 'ט', dayOfWeek: 4, events: [] },
               { name: 'י', dayOfWeek: 5, events: [] },
               { name: 'יא', dayOfWeek: 6, events: [] },
               { name: 'יב', dayOfWeek: 7, events: [] },
               { name: 'יג', dayOfWeek: 1, events: [] },
               { name: 'יד', dayOfWeek: 2, events: [] },
               { name: 'טו', dayOfWeek: 3, events: [{ type: '🥬', text: 'יום טוב פסח' }] },
               { name: 'טז', dayOfWeek: 4, events: [{ type: '🥬', text: 'א דחול המועד' }] },
               { name: 'יז', dayOfWeek: 5, events: [{ type: '🥬', text: 'ב דחול המועד' }] },
               { name: 'יח', dayOfWeek: 6, events: [{ type: '🥬', text: 'ג דחול המועד' }] },
               { name: 'יט', dayOfWeek: 7, events: [{ type: '🥬', text: 'ד דחול המועד' }] },
               { name: 'כ', dayOfWeek: 1, events: [{ type: '🥬', text: 'ה דחול המועד' }] },
               { name: 'כא', dayOfWeek: 2, events: [{ type: '🥬', text: 'שביעי של פסח' }] },
               { name: 'כב', dayOfWeek: 3, events: [] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [] },
               { name: 'כו', dayOfWeek: 7, events: [] },
               { name: 'כז', dayOfWeek: 1, events: [] },
               { name: 'כח', dayOfWeek: 2, events: [] },
               { name: 'כט', dayOfWeek: 3, events: [] },
               { name: 'ל', dayOfWeek: 4, events: [] },
           ]
       },
       {
           name: 'אייר',
           Days: [
               { name: 'א', dayOfWeek: 5, events: [] },
               { name: 'ב', dayOfWeek: 6, events: [] },
               { name: 'ג', dayOfWeek: 4, events: [] },
               { name: 'ד', dayOfWeek: 5, events: [] },
               { name: 'ה', dayOfWeek: 6, events: [] },
               { name: 'ו', dayOfWeek: 7, events: [] },
               { name: 'ז', dayOfWeek: 1, events: [] },
               { name: 'ח', dayOfWeek: 2, events: [] },
               { name: 'ט', dayOfWeek: 3, events: [] },
               { name: 'י', dayOfWeek: 4, events: [] },
               { name: 'יא', dayOfWeek: 5, events: [] },
               { name: 'יב', dayOfWeek: 6, events: [] },
               { name: 'יג', dayOfWeek: 4, events: [] },
               { name: 'יד', dayOfWeek: 5, events: [] },
               { name: 'טו', dayOfWeek: 6, events: [] },
               { name: 'טז', dayOfWeek: 7, events: [] },
               { name: 'יז', dayOfWeek: 1, events: [] },
               { name: 'יח', dayOfWeek: 2, events: [{ type: '🔥', text: 'לג בעומר' }] },
               { name: 'יט', dayOfWeek: 3, events: [] },
               { name: 'כ', dayOfWeek: 4, events: [] },
               { name: 'כא', dayOfWeek: 5, events: [] },
               { name: 'כב', dayOfWeek: 6, events: [] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [] },
               { name: 'כו', dayOfWeek: 7, events: [] },
               { name: 'כז', dayOfWeek: 1, events: [] },
               { name: 'כח', dayOfWeek: 2, events: [] },
               { name: 'כט', dayOfWeek: 3, events: [] },
           ]
       }, {
           name: 'סיוון',
           Days: [
               { name: 'א', dayOfWeek: 3, events: [] },
               { name: 'ב', dayOfWeek: 4, events: [] },
               { name: 'ג', dayOfWeek: 5, events: [] },
               { name: 'ד', dayOfWeek: 6, events: [] },
               { name: 'ה', dayOfWeek: 7, events: [] },
               { name: 'ו', dayOfWeek: 1, events: [{ type: '📖', text: 'יום טוב שבועות' }] },
               { name: 'ז', dayOfWeek: 2, events: [] },
               { name: 'ח', dayOfWeek: 3, events: [] },
               { name: 'ט', dayOfWeek: 4, events: [] },
               { name: 'י', dayOfWeek: 5, events: [] },
               { name: 'יא', dayOfWeek: 6, events: [] },
               { name: 'יב', dayOfWeek: 7, events: [] },
               { name: 'יג', dayOfWeek: 1, events: [] },
               { name: 'יד', dayOfWeek: 2, events: [] },
               { name: 'טו', dayOfWeek: 3, events: [] },
               { name: 'טז', dayOfWeek: 4, events: [] },
               { name: 'יז', dayOfWeek: 5, events: [] },
               { name: 'יח', dayOfWeek: 6, events: [] },
               { name: 'יט', dayOfWeek: 7, events: [] },
               { name: 'כ', dayOfWeek: 1, events: [] },
               { name: 'כא', dayOfWeek: 2, events: [] },
               { name: 'כב', dayOfWeek: 3, events: [] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [] },
               { name: 'כו', dayOfWeek: 7, events: [] },
               { name: 'כז', dayOfWeek: 1, events: [] },
               { name: 'כח', dayOfWeek: 2, events: [] },
               { name: 'כט', dayOfWeek: 3, events: [] },
               { name: 'ל', dayOfWeek: 4, events: [] },
           ]
       },
       {
           name: 'תמוז',
           Days: [
               { name: 'א', dayOfWeek: 5, events: [] },
               { name: 'ב', dayOfWeek: 6, events: [] },
               { name: 'ג', dayOfWeek: 4, events: [] },
               { name: 'ד', dayOfWeek: 5, events: [] },
               { name: 'ה', dayOfWeek: 6, events: [] },
               { name: 'ו', dayOfWeek: 7, events: [] },
               { name: 'ז', dayOfWeek: 1, events: [] },
               { name: 'ח', dayOfWeek: 2, events: [] },
               { name: 'ט', dayOfWeek: 3, events: [] },
               { name: 'י', dayOfWeek: 4, events: [] },
               { name: 'יא', dayOfWeek: 5, events: [] },
               { name: 'יב', dayOfWeek: 6, events: [] },
               { name: 'יג', dayOfWeek: 4, events: [] },
               { name: 'יד', dayOfWeek: 5, events: [] },
               { name: 'טו', dayOfWeek: 6, events: [] },
               { name: 'טז', dayOfWeek: 7, events: [] },
               { name: 'יז', dayOfWeek: 1, events: [{ type: '❎', text: 'צום שבעה עשר בתמוז' }] },
               { name: 'יח', dayOfWeek: 2, events: [] },
               { name: 'יט', dayOfWeek: 3, events: [] },
               { name: 'כ', dayOfWeek: 4, events: [] },
               { name: 'כא', dayOfWeek: 5, events: [] },
               { name: 'כב', dayOfWeek: 6, events: [] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [] },
               { name: 'כו', dayOfWeek: 7, events: [] },
               { name: 'כז', dayOfWeek: 1, events: [] },
               { name: 'כח', dayOfWeek: 2, events: [] },
               { name: 'כט', dayOfWeek: 3, events: [] },
           ]
       },
       {
           name: 'אב',
           Days: [
               { name: 'א', dayOfWeek: 3, events: [] },
               { name: 'ב', dayOfWeek: 4, events: [] },
               { name: 'ג', dayOfWeek: 5, events: [] },
               { name: 'ד', dayOfWeek: 6, events: [] },
               { name: 'ה', dayOfWeek: 7, events: [] },
               { name: 'ו', dayOfWeek: 1, events: [] },
               { name: 'ז', dayOfWeek: 2, events: [] },
               { name: 'ח', dayOfWeek: 3, events: [] },
               { name: 'ט', dayOfWeek: 4, events: [{ type: '❎', text: 'צום תשעה באב' }] },
               { name: 'י', dayOfWeek: 5, events: [] },
               { name: 'יא', dayOfWeek: 6, events: [] },
               { name: 'יב', dayOfWeek: 7, events: [] },
               { name: 'יג', dayOfWeek: 1, events: [] },
               { name: 'יד', dayOfWeek: 2, events: [] },
               { name: 'טו', dayOfWeek: 3, events: [] },
               { name: 'טז', dayOfWeek: 4, events: [] },
               { name: 'יז', dayOfWeek: 5, events: [] },
               { name: 'יח', dayOfWeek: 6, events: [] },
               { name: 'יט', dayOfWeek: 7, events: [] },
               { name: 'כ', dayOfWeek: 1, events: [] },
               { name: 'כא', dayOfWeek: 2, events: [] },
               { name: 'כב', dayOfWeek: 3, events: [] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [] },
               { name: 'כו', dayOfWeek: 7, events: [] },
               { name: 'כז', dayOfWeek: 1, events: [] },
               { name: 'כח', dayOfWeek: 2, events: [] },
               { name: 'כט', dayOfWeek: 3, events: [] },
               { name: 'ל', dayOfWeek: 4, events: [] },
           ]
       },
       {
           name: 'אלול',
           Days: [
               { name: 'א', dayOfWeek: 5, events: [] },
               { name: 'ב', dayOfWeek: 6, events: [] },
               { name: 'ג', dayOfWeek: 4, events: [] },
               { name: 'ד', dayOfWeek: 5, events: [] },
               { name: 'ה', dayOfWeek: 6, events: [] },
               { name: 'ו', dayOfWeek: 7, events: [] },
               { name: 'ז', dayOfWeek: 1, events: [] },
               { name: 'ח', dayOfWeek: 2, events: [] },
               { name: 'ט', dayOfWeek: 3, events: [] },
               { name: 'י', dayOfWeek: 4, events: [] },
               { name: 'יא', dayOfWeek: 5, events: [] },
               { name: 'יב', dayOfWeek: 6, events: [] },
               { name: 'יג', dayOfWeek: 4, events: [] },
               { name: 'יד', dayOfWeek: 5, events: [] },
               { name: 'טו', dayOfWeek: 6, events: [] },
               { name: 'טז', dayOfWeek: 7, events: [] },
               { name: 'יז', dayOfWeek: 1, events: [] },
               { name: 'יח', dayOfWeek: 2, events: [] },
               { name: 'יט', dayOfWeek: 3, events: [] },
               { name: 'כ', dayOfWeek: 4, events: [] },
               { name: 'כא', dayOfWeek: 5, events: [] },
               { name: 'כב', dayOfWeek: 6, events: [] },
               { name: 'כג', dayOfWeek: 4, events: [] },
               { name: 'כד', dayOfWeek: 5, events: [] },
               { name: 'כה', dayOfWeek: 6, events: [] },
               { name: 'כו', dayOfWeek: 7, events: [] },
               { name: 'כז', dayOfWeek: 1, events: [] },
               { name: 'כח', dayOfWeek: 2, events: [] },
               { name: 'כט', dayOfWeek: 3, events: [] },
           ]
       },
   ]
 })
    return <>
    {
    !flag?
    <NewCalander mysetName={setName} mysetBacColor={setBacColor} mysetColor={setcolorTest} add={add} setBasicCalender={setBasicCalender} setflag={setflag}></NewCalander>
    :
    <div>
    <div className="form-wrapper" >
    <NewEvent basicCalender={basicCalender} setBasicCalender={setBasicCalender} name={name}></NewEvent>
    <NewCalander mysetName={setName} mysetBacColor={setBacColor} mysetColor={setcolorTest} add={add} setBasicCalender={setBasicCalender} setflag={setflag}></NewCalander>
    </div>
    <div className="main-content">
    <Calander basicCalender={basicCalender} myName={name} myBacColor={bacColor} myColor={colorTest} ></Calander>
    </div>
    </div>
    }
    </>
}